//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiexamen.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ResultRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblExamen", Namespace="http://schemas.datacontract.org/2004/07/ModelExamen")]
    [System.SerializableAttribute()]
    public partial class tblExamen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idExamenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExamen {
            get {
                return this.idExamenField;
            }
            set {
                if ((this.idExamenField.Equals(value) != true)) {
                    this.idExamenField = value;
                    this.RaisePropertyChanged("idExamen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AgregarExamen", ReplyAction="http://tempuri.org/IService/AgregarExamenResponse")]
        apiexamen.ServiceReference1.ResultRequest AgregarExamen(int id, string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AgregarExamen", ReplyAction="http://tempuri.org/IService/AgregarExamenResponse")]
        System.Threading.Tasks.Task<apiexamen.ServiceReference1.ResultRequest> AgregarExamenAsync(int id, string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarExamen", ReplyAction="http://tempuri.org/IService/ActualizarExamenResponse")]
        apiexamen.ServiceReference1.ResultRequest ActualizarExamen(int id, string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarExamen", ReplyAction="http://tempuri.org/IService/ActualizarExamenResponse")]
        System.Threading.Tasks.Task<apiexamen.ServiceReference1.ResultRequest> ActualizarExamenAsync(int id, string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarExamen", ReplyAction="http://tempuri.org/IService/EliminarExamenResponse")]
        apiexamen.ServiceReference1.ResultRequest EliminarExamen(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarExamen", ReplyAction="http://tempuri.org/IService/EliminarExamenResponse")]
        System.Threading.Tasks.Task<apiexamen.ServiceReference1.ResultRequest> EliminarExamenAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarExamen", ReplyAction="http://tempuri.org/IService/ConsultarExamenResponse")]
        apiexamen.ServiceReference1.tblExamen[] ConsultarExamen(int id, string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarExamen", ReplyAction="http://tempuri.org/IService/ConsultarExamenResponse")]
        System.Threading.Tasks.Task<apiexamen.ServiceReference1.tblExamen[]> ConsultarExamenAsync(int id, string nombre, string descripcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : apiexamen.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<apiexamen.ServiceReference1.IService>, apiexamen.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public apiexamen.ServiceReference1.ResultRequest AgregarExamen(int id, string nombre, string descripcion) {
            return base.Channel.AgregarExamen(id, nombre, descripcion);
        }
        
        public System.Threading.Tasks.Task<apiexamen.ServiceReference1.ResultRequest> AgregarExamenAsync(int id, string nombre, string descripcion) {
            return base.Channel.AgregarExamenAsync(id, nombre, descripcion);
        }
        
        public apiexamen.ServiceReference1.ResultRequest ActualizarExamen(int id, string nombre, string descripcion) {
            return base.Channel.ActualizarExamen(id, nombre, descripcion);
        }
        
        public System.Threading.Tasks.Task<apiexamen.ServiceReference1.ResultRequest> ActualizarExamenAsync(int id, string nombre, string descripcion) {
            return base.Channel.ActualizarExamenAsync(id, nombre, descripcion);
        }
        
        public apiexamen.ServiceReference1.ResultRequest EliminarExamen(int id) {
            return base.Channel.EliminarExamen(id);
        }
        
        public System.Threading.Tasks.Task<apiexamen.ServiceReference1.ResultRequest> EliminarExamenAsync(int id) {
            return base.Channel.EliminarExamenAsync(id);
        }
        
        public apiexamen.ServiceReference1.tblExamen[] ConsultarExamen(int id, string nombre, string descripcion) {
            return base.Channel.ConsultarExamen(id, nombre, descripcion);
        }
        
        public System.Threading.Tasks.Task<apiexamen.ServiceReference1.tblExamen[]> ConsultarExamenAsync(int id, string nombre, string descripcion) {
            return base.Channel.ConsultarExamenAsync(id, nombre, descripcion);
        }
    }
}
