//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiexamen.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BdiexamenEntities1 : DbContext
    {
        public BdiexamenEntities1()
            : base("name=BdiexamenEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblExamen> tblExamen { get; set; }
    
        public virtual int spActualizar(Nullable<int> idExamen, string nombre, string descripcion)
        {
            var idExamenParameter = idExamen.HasValue ?
                new ObjectParameter("idExamen", idExamen) :
                new ObjectParameter("idExamen", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spActualizar", idExamenParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int spAgregar(Nullable<int> idExamen, string nombre, string descripcion)
        {
            var idExamenParameter = idExamen.HasValue ?
                new ObjectParameter("idExamen", idExamen) :
                new ObjectParameter("idExamen", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregar", idExamenParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<spConsultar_Result> spConsultar(Nullable<int> idExamen)
        {
            var idExamenParameter = idExamen.HasValue ?
                new ObjectParameter("idExamen", idExamen) :
                new ObjectParameter("idExamen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultar_Result>("spConsultar", idExamenParameter);
        }
    
        public virtual int spEliminar(Nullable<int> idExamen)
        {
            var idExamenParameter = idExamen.HasValue ?
                new ObjectParameter("idExamen", idExamen) :
                new ObjectParameter("idExamen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminar", idExamenParameter);
        }
    }
}
